name: Update Waka stats
on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Waka stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### content
          SHOW_TITLE: false # optional
          BLOCKS: üêæü¶ä # optional
          TIME_RANGE: last_30_days # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: false # optional
          SHOW_MASKED_TIME: true # optional
          STOP_AT_OTHER: true # optional
          ### commit
          COMMIT_MESSAGE: ‚ú® Updated waka-readme graph with new metrics
          COMMITTER_NAME: Simon Pham
          COMMITTER_EMAIL: simonpham.dn@gmail.com
          AUTHOR_NAME: Simon Pham
          AUTHOR_EMAIL: simonpham.dn@gmail.com
